version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0
  node: circleci/node@4.1

executors:
  node:
    docker:
      - image: cimg/node:15.1
  deployer:
    docker:
      - image: cimg/python:3.6

jobs:
  build:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - run: npm run build

  deploy:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - aws-s3/sync:
          from: build
          to: s3://greenbacks.app

  lint:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint

  test:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - run: npm run test

  test_pr:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - run: npm run check

  typecheck:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - run: npm run typecheck

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: main
  deploy:
    jobs:
      - deploy:
          context:
            - aws
          filters:
            branches:
              only: main
  lint:
    jobs:
      - lint:
          filters:
            branches:
              ignore: main
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: main
  typecheck:
    jobs:
      - typecheck:
          filters:
            branches:
              ignore: main
