version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0
  node: circleci/node@4.1

executors:
  node:
    docker:
      - image: cimg/node:15.1
  deployer:
    docker:
      - image: cimg/python:3.6

jobs:
  test_pr:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - run: npm run check

  deploy:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - aws-s3/sync:
          from: build
          to: s3://greenbacks.app

workflows:
  version: 2
  test_pr:
    jobs:
      - test_pr:
          filters:
            branches:
              ignore: main
  deploy:
    jobs:
      - deploy:
          context:
            - aws
