version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12.2.0

jobs:
  build_and_test:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-v1-{{ checksum "package.json" }}
            - dependencies-v1
      - run: make install
      - save_cache:
          key: dependencies-v1-{{ checksum "package.json" }}
      - run: make lint

  install:
    docker:
      - image: circleci/node:12.2.0
    steps:
      - checkout
      - run: make install
      - persist_to_workspace:
          root: /home/circleci/project/
          paths:
            - node_modules

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - build_and_test:
          filters:
            branches:
              ignore: main
